version: '3.1'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prog_blog
      MYSQL_DATABASE: prog_blog
      MYSQL_USER: olga
      MYSQL_PASSWORD: olga22
    ports:
      - "3306:3306"

  prog-blog:
    build:
      context: .
    ports:
      - "8001:8000"
    depends_on:
      - mysql
    environment:
      DEBUG: "False"
      DB_NAME: "prog_blog"
      DB_USER: "olga"
      DB_PASSWORD: "olga22"
      DB_HOST: "mysql"
      DB_PORT: 3306
